###
POST http://localhost:8080/api/v1/boards
Content-Type: application/json

{
  "id": 2,
  "title": "제목1",
  "content": "내용내용",
  "author": "우주완"
}

###
GET http://localhost:8080/api/v1/boards/list

###
GET http://localhost:8080/api/v1/boards/2

###
DELETE http://localhost:8080/api/v1/boards/3